# Generated by Django 3.0.4 on 2020-03-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
    ]
