# Generated by Django 3.0.4 on 2020-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('red', 0), ('orange', 1), ('white', 2)], max_length=10),
        ),
    ]
