# Generated by Django 3.0.4 on 2020-04-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200330_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(0, 'red'), (1, 'orange'), (2, 'white')], max_length=10),
        ),
    ]
